----------------------------------------------------------------------------------------------------
CREATE TABLE public.sales_order_header
(
  sales_order_id INTEGER NOT NULL,
  order_date TEXT,
  due_date TEXT,
  ship_date TEXT,
  status TEXT,
  online_order_flag TEXT,
  sales_order_number TEXT,
  purchase_order_number TEXT,
  account_number TEXT,
  customer_id TEXT,
  sales_person_id TEXT,
  territory_id TEXT,
  bill_to_address_id TEXT,
  ship_to_address_id TEXT,
  ship_method_id TEXT,
  credit_card_id TEXT,
  credit_card_approval_code TEXT,
  currency_rate_id TEXT,
  sub_total TEXT,
  tax_amount TEXT,
  freight TEXT,
  total_due TEXT,
  comment TEXT,
  modified_date TEXT
);

ALTER TABLE public.sales_order_header
  ALTER COLUMN sales_order_id ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public.sales_order_header
  ADD CONSTRAINT contacts_pkey PRIMARY KEY(sales_order_id);

ALTER TABLE public.sales_order_header
  OWNER TO dbuser;

